/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProcessosRouteImport } from './routes/app.processos'
import { Route as AppPeritosRouteImport } from './routes/app.peritos'
import { Route as AppPericiasRouteImport } from './routes/app.pericias'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppProcessosNovoRouteImport } from './routes/app.processos.novo'
import { Route as AppProcessosIdRouteImport } from './routes/app.processos.$id'
import { Route as AppPeritosIdRouteImport } from './routes/app.peritos.$id'
import { Route as AppPericiasNovaRouteImport } from './routes/app.pericias.nova'
import { Route as AppPericiasIdRouteImport } from './routes/app.pericias.$id'
import { Route as AppClientesNovoRouteImport } from './routes/app.clientes.novo'
import { Route as AppClientesIdRouteImport } from './routes/app.clientes.$id'
import { Route as AppProcessosIdEditarRouteImport } from './routes/app.processos.$id.editar'
import { Route as AppPericiasIdEditarRouteImport } from './routes/app.pericias.$id.editar'
import { Route as AppClientesIdEditarRouteImport } from './routes/app.clientes.$id.editar'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessosRoute = AppProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => AppRoute,
} as any)
const AppPeritosRoute = AppPeritosRouteImport.update({
  id: '/peritos',
  path: '/peritos',
  getParentRoute: () => AppRoute,
} as any)
const AppPericiasRoute = AppPericiasRouteImport.update({
  id: '/pericias',
  path: '/pericias',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessosNovoRoute = AppProcessosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppProcessosRoute,
} as any)
const AppProcessosIdRoute = AppProcessosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProcessosRoute,
} as any)
const AppPeritosIdRoute = AppPeritosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPeritosRoute,
} as any)
const AppPericiasNovaRoute = AppPericiasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppPericiasRoute,
} as any)
const AppPericiasIdRoute = AppPericiasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPericiasRoute,
} as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppProcessosIdEditarRoute = AppProcessosIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AppProcessosIdRoute,
} as any)
const AppPericiasIdEditarRoute = AppPericiasIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AppPericiasIdRoute,
} as any)
const AppClientesIdEditarRoute = AppClientesIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AppClientesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/pericias': typeof AppPericiasRouteWithChildren
  '/app/peritos': typeof AppPeritosRouteWithChildren
  '/app/processos': typeof AppProcessosRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/clientes/$id': typeof AppClientesIdRouteWithChildren
  '/app/clientes/novo': typeof AppClientesNovoRoute
  '/app/pericias/$id': typeof AppPericiasIdRouteWithChildren
  '/app/pericias/nova': typeof AppPericiasNovaRoute
  '/app/peritos/$id': typeof AppPeritosIdRoute
  '/app/processos/$id': typeof AppProcessosIdRouteWithChildren
  '/app/processos/novo': typeof AppProcessosNovoRoute
  '/app/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/app/pericias/$id/editar': typeof AppPericiasIdEditarRoute
  '/app/processos/$id/editar': typeof AppProcessosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/pericias': typeof AppPericiasRouteWithChildren
  '/app/peritos': typeof AppPeritosRouteWithChildren
  '/app/processos': typeof AppProcessosRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/clientes/$id': typeof AppClientesIdRouteWithChildren
  '/app/clientes/novo': typeof AppClientesNovoRoute
  '/app/pericias/$id': typeof AppPericiasIdRouteWithChildren
  '/app/pericias/nova': typeof AppPericiasNovaRoute
  '/app/peritos/$id': typeof AppPeritosIdRoute
  '/app/processos/$id': typeof AppProcessosIdRouteWithChildren
  '/app/processos/novo': typeof AppProcessosNovoRoute
  '/app/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/app/pericias/$id/editar': typeof AppPericiasIdEditarRoute
  '/app/processos/$id/editar': typeof AppProcessosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/pericias': typeof AppPericiasRouteWithChildren
  '/app/peritos': typeof AppPeritosRouteWithChildren
  '/app/processos': typeof AppProcessosRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/clientes/$id': typeof AppClientesIdRouteWithChildren
  '/app/clientes/novo': typeof AppClientesNovoRoute
  '/app/pericias/$id': typeof AppPericiasIdRouteWithChildren
  '/app/pericias/nova': typeof AppPericiasNovaRoute
  '/app/peritos/$id': typeof AppPeritosIdRoute
  '/app/processos/$id': typeof AppProcessosIdRouteWithChildren
  '/app/processos/novo': typeof AppProcessosNovoRoute
  '/app/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/app/pericias/$id/editar': typeof AppPericiasIdEditarRoute
  '/app/processos/$id/editar': typeof AppProcessosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contato'
    | '/criar-conta'
    | '/entrar'
    | '/recuperar-senha'
    | '/servicos'
    | '/sobre'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/pericias'
    | '/app/peritos'
    | '/app/processos'
    | '/app/'
    | '/app/clientes/$id'
    | '/app/clientes/novo'
    | '/app/pericias/$id'
    | '/app/pericias/nova'
    | '/app/peritos/$id'
    | '/app/processos/$id'
    | '/app/processos/novo'
    | '/app/clientes/$id/editar'
    | '/app/pericias/$id/editar'
    | '/app/processos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/criar-conta'
    | '/entrar'
    | '/recuperar-senha'
    | '/servicos'
    | '/sobre'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/pericias'
    | '/app/peritos'
    | '/app/processos'
    | '/app'
    | '/app/clientes/$id'
    | '/app/clientes/novo'
    | '/app/pericias/$id'
    | '/app/pericias/nova'
    | '/app/peritos/$id'
    | '/app/processos/$id'
    | '/app/processos/novo'
    | '/app/clientes/$id/editar'
    | '/app/pericias/$id/editar'
    | '/app/processos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contato'
    | '/criar-conta'
    | '/entrar'
    | '/recuperar-senha'
    | '/servicos'
    | '/sobre'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/pericias'
    | '/app/peritos'
    | '/app/processos'
    | '/app/'
    | '/app/clientes/$id'
    | '/app/clientes/novo'
    | '/app/pericias/$id'
    | '/app/pericias/nova'
    | '/app/peritos/$id'
    | '/app/processos/$id'
    | '/app/processos/novo'
    | '/app/clientes/$id/editar'
    | '/app/pericias/$id/editar'
    | '/app/processos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processos': {
      id: '/app/processos'
      path: '/processos'
      fullPath: '/app/processos'
      preLoaderRoute: typeof AppProcessosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/peritos': {
      id: '/app/peritos'
      path: '/peritos'
      fullPath: '/app/peritos'
      preLoaderRoute: typeof AppPeritosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pericias': {
      id: '/app/pericias'
      path: '/pericias'
      fullPath: '/app/pericias'
      preLoaderRoute: typeof AppPericiasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processos/novo': {
      id: '/app/processos/novo'
      path: '/novo'
      fullPath: '/app/processos/novo'
      preLoaderRoute: typeof AppProcessosNovoRouteImport
      parentRoute: typeof AppProcessosRoute
    }
    '/app/processos/$id': {
      id: '/app/processos/$id'
      path: '/$id'
      fullPath: '/app/processos/$id'
      preLoaderRoute: typeof AppProcessosIdRouteImport
      parentRoute: typeof AppProcessosRoute
    }
    '/app/peritos/$id': {
      id: '/app/peritos/$id'
      path: '/$id'
      fullPath: '/app/peritos/$id'
      preLoaderRoute: typeof AppPeritosIdRouteImport
      parentRoute: typeof AppPeritosRoute
    }
    '/app/pericias/nova': {
      id: '/app/pericias/nova'
      path: '/nova'
      fullPath: '/app/pericias/nova'
      preLoaderRoute: typeof AppPericiasNovaRouteImport
      parentRoute: typeof AppPericiasRoute
    }
    '/app/pericias/$id': {
      id: '/app/pericias/$id'
      path: '/$id'
      fullPath: '/app/pericias/$id'
      preLoaderRoute: typeof AppPericiasIdRouteImport
      parentRoute: typeof AppPericiasRoute
    }
    '/app/clientes/novo': {
      id: '/app/clientes/novo'
      path: '/novo'
      fullPath: '/app/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/app/clientes/$id': {
      id: '/app/clientes/$id'
      path: '/$id'
      fullPath: '/app/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/app/processos/$id/editar': {
      id: '/app/processos/$id/editar'
      path: '/editar'
      fullPath: '/app/processos/$id/editar'
      preLoaderRoute: typeof AppProcessosIdEditarRouteImport
      parentRoute: typeof AppProcessosIdRoute
    }
    '/app/pericias/$id/editar': {
      id: '/app/pericias/$id/editar'
      path: '/editar'
      fullPath: '/app/pericias/$id/editar'
      preLoaderRoute: typeof AppPericiasIdEditarRouteImport
      parentRoute: typeof AppPericiasIdRoute
    }
    '/app/clientes/$id/editar': {
      id: '/app/clientes/$id/editar'
      path: '/editar'
      fullPath: '/app/clientes/$id/editar'
      preLoaderRoute: typeof AppClientesIdEditarRouteImport
      parentRoute: typeof AppClientesIdRoute
    }
  }
}

interface AppClientesIdRouteChildren {
  AppClientesIdEditarRoute: typeof AppClientesIdEditarRoute
}

const AppClientesIdRouteChildren: AppClientesIdRouteChildren = {
  AppClientesIdEditarRoute: AppClientesIdEditarRoute,
}

const AppClientesIdRouteWithChildren = AppClientesIdRoute._addFileChildren(
  AppClientesIdRouteChildren,
)

interface AppClientesRouteChildren {
  AppClientesIdRoute: typeof AppClientesIdRouteWithChildren
  AppClientesNovoRoute: typeof AppClientesNovoRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesIdRoute: AppClientesIdRouteWithChildren,
  AppClientesNovoRoute: AppClientesNovoRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppPericiasIdRouteChildren {
  AppPericiasIdEditarRoute: typeof AppPericiasIdEditarRoute
}

const AppPericiasIdRouteChildren: AppPericiasIdRouteChildren = {
  AppPericiasIdEditarRoute: AppPericiasIdEditarRoute,
}

const AppPericiasIdRouteWithChildren = AppPericiasIdRoute._addFileChildren(
  AppPericiasIdRouteChildren,
)

interface AppPericiasRouteChildren {
  AppPericiasIdRoute: typeof AppPericiasIdRouteWithChildren
  AppPericiasNovaRoute: typeof AppPericiasNovaRoute
}

const AppPericiasRouteChildren: AppPericiasRouteChildren = {
  AppPericiasIdRoute: AppPericiasIdRouteWithChildren,
  AppPericiasNovaRoute: AppPericiasNovaRoute,
}

const AppPericiasRouteWithChildren = AppPericiasRoute._addFileChildren(
  AppPericiasRouteChildren,
)

interface AppPeritosRouteChildren {
  AppPeritosIdRoute: typeof AppPeritosIdRoute
}

const AppPeritosRouteChildren: AppPeritosRouteChildren = {
  AppPeritosIdRoute: AppPeritosIdRoute,
}

const AppPeritosRouteWithChildren = AppPeritosRoute._addFileChildren(
  AppPeritosRouteChildren,
)

interface AppProcessosIdRouteChildren {
  AppProcessosIdEditarRoute: typeof AppProcessosIdEditarRoute
}

const AppProcessosIdRouteChildren: AppProcessosIdRouteChildren = {
  AppProcessosIdEditarRoute: AppProcessosIdEditarRoute,
}

const AppProcessosIdRouteWithChildren = AppProcessosIdRoute._addFileChildren(
  AppProcessosIdRouteChildren,
)

interface AppProcessosRouteChildren {
  AppProcessosIdRoute: typeof AppProcessosIdRouteWithChildren
  AppProcessosNovoRoute: typeof AppProcessosNovoRoute
}

const AppProcessosRouteChildren: AppProcessosRouteChildren = {
  AppProcessosIdRoute: AppProcessosIdRouteWithChildren,
  AppProcessosNovoRoute: AppProcessosNovoRoute,
}

const AppProcessosRouteWithChildren = AppProcessosRoute._addFileChildren(
  AppProcessosRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppPericiasRoute: typeof AppPericiasRouteWithChildren
  AppPeritosRoute: typeof AppPeritosRouteWithChildren
  AppProcessosRoute: typeof AppProcessosRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppPericiasRoute: AppPericiasRouteWithChildren,
  AppPeritosRoute: AppPeritosRouteWithChildren,
  AppProcessosRoute: AppProcessosRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
