/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ProfissoesRouteImport } from './routes/profissoes'
import { Route as ProdutoRouteImport } from './routes/produto'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppProcessosIndexRouteImport } from './routes/app.processos.index'
import { Route as AppPeritosIndexRouteImport } from './routes/app.peritos.index'
import { Route as AppPericiasIndexRouteImport } from './routes/app.pericias.index'
import { Route as AppClientesIndexRouteImport } from './routes/app.clientes.index'
import { Route as AppProcessosNovoRouteImport } from './routes/app.processos.novo'
import { Route as AppPeritosNovoRouteImport } from './routes/app.peritos.novo'
import { Route as AppPericiasNovaRouteImport } from './routes/app.pericias.nova'
import { Route as AppClientesNovoRouteImport } from './routes/app.clientes.novo'
import { Route as AppProcessosIdIndexRouteImport } from './routes/app.processos.$id.index'
import { Route as AppPeritosIdIndexRouteImport } from './routes/app.peritos.$id.index'
import { Route as AppPericiasIdIndexRouteImport } from './routes/app.pericias.$id.index'
import { Route as AppClientesIdIndexRouteImport } from './routes/app.clientes.$id.index'
import { Route as AppProcessosIdEditarRouteImport } from './routes/app.processos.$id.editar'
import { Route as AppPeritosIdEditarRouteImport } from './routes/app.peritos.$id.editar'
import { Route as AppPericiasIdEditarRouteImport } from './routes/app.pericias.$id.editar'
import { Route as AppClientesIdEditarRouteImport } from './routes/app.clientes.$id.editar'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissoesRoute = ProfissoesRouteImport.update({
  id: '/profissoes',
  path: '/profissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessosIndexRoute = AppProcessosIndexRouteImport.update({
  id: '/processos/',
  path: '/processos/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeritosIndexRoute = AppPeritosIndexRouteImport.update({
  id: '/peritos/',
  path: '/peritos/',
  getParentRoute: () => AppRoute,
} as any)
const AppPericiasIndexRoute = AppPericiasIndexRouteImport.update({
  id: '/pericias/',
  path: '/pericias/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessosNovoRoute = AppProcessosNovoRouteImport.update({
  id: '/processos/novo',
  path: '/processos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppPeritosNovoRoute = AppPeritosNovoRouteImport.update({
  id: '/peritos/novo',
  path: '/peritos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppPericiasNovaRoute = AppPericiasNovaRouteImport.update({
  id: '/pericias/nova',
  path: '/pericias/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessosIdIndexRoute = AppProcessosIdIndexRouteImport.update({
  id: '/processos/$id/',
  path: '/processos/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeritosIdIndexRoute = AppPeritosIdIndexRouteImport.update({
  id: '/peritos/$id/',
  path: '/peritos/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppPericiasIdIndexRoute = AppPericiasIdIndexRouteImport.update({
  id: '/pericias/$id/',
  path: '/pericias/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdIndexRoute = AppClientesIdIndexRouteImport.update({
  id: '/clientes/$id/',
  path: '/clientes/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessosIdEditarRoute = AppProcessosIdEditarRouteImport.update({
  id: '/processos/$id/editar',
  path: '/processos/$id/editar',
  getParentRoute: () => AppRoute,
} as any)
const AppPeritosIdEditarRoute = AppPeritosIdEditarRouteImport.update({
  id: '/peritos/$id/editar',
  path: '/peritos/$id/editar',
  getParentRoute: () => AppRoute,
} as any)
const AppPericiasIdEditarRoute = AppPericiasIdEditarRouteImport.update({
  id: '/pericias/$id/editar',
  path: '/pericias/$id/editar',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdEditarRoute = AppClientesIdEditarRouteImport.update({
  id: '/clientes/$id/editar',
  path: '/clientes/$id/editar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/planos': typeof PlanosRoute
  '/produto': typeof ProdutoRoute
  '/profissoes': typeof ProfissoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/recursos': typeof RecursosRoute
  '/seguranca': typeof SegurancaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/novo': typeof AppClientesNovoRoute
  '/app/pericias/nova': typeof AppPericiasNovaRoute
  '/app/peritos/novo': typeof AppPeritosNovoRoute
  '/app/processos/novo': typeof AppProcessosNovoRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/pericias/': typeof AppPericiasIndexRoute
  '/app/peritos/': typeof AppPeritosIndexRoute
  '/app/processos/': typeof AppProcessosIndexRoute
  '/app/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/app/pericias/$id/editar': typeof AppPericiasIdEditarRoute
  '/app/peritos/$id/editar': typeof AppPeritosIdEditarRoute
  '/app/processos/$id/editar': typeof AppProcessosIdEditarRoute
  '/app/clientes/$id/': typeof AppClientesIdIndexRoute
  '/app/pericias/$id/': typeof AppPericiasIdIndexRoute
  '/app/peritos/$id/': typeof AppPeritosIdIndexRoute
  '/app/processos/$id/': typeof AppProcessosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/planos': typeof PlanosRoute
  '/produto': typeof ProdutoRoute
  '/profissoes': typeof ProfissoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/recursos': typeof RecursosRoute
  '/seguranca': typeof SegurancaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app': typeof AppIndexRoute
  '/app/clientes/novo': typeof AppClientesNovoRoute
  '/app/pericias/nova': typeof AppPericiasNovaRoute
  '/app/peritos/novo': typeof AppPeritosNovoRoute
  '/app/processos/novo': typeof AppProcessosNovoRoute
  '/app/clientes': typeof AppClientesIndexRoute
  '/app/pericias': typeof AppPericiasIndexRoute
  '/app/peritos': typeof AppPeritosIndexRoute
  '/app/processos': typeof AppProcessosIndexRoute
  '/app/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/app/pericias/$id/editar': typeof AppPericiasIdEditarRoute
  '/app/peritos/$id/editar': typeof AppPeritosIdEditarRoute
  '/app/processos/$id/editar': typeof AppProcessosIdEditarRoute
  '/app/clientes/$id': typeof AppClientesIdIndexRoute
  '/app/pericias/$id': typeof AppPericiasIdIndexRoute
  '/app/peritos/$id': typeof AppPeritosIdIndexRoute
  '/app/processos/$id': typeof AppProcessosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/planos': typeof PlanosRoute
  '/produto': typeof ProdutoRoute
  '/profissoes': typeof ProfissoesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/recursos': typeof RecursosRoute
  '/seguranca': typeof SegurancaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/novo': typeof AppClientesNovoRoute
  '/app/pericias/nova': typeof AppPericiasNovaRoute
  '/app/peritos/novo': typeof AppPeritosNovoRoute
  '/app/processos/novo': typeof AppProcessosNovoRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/pericias/': typeof AppPericiasIndexRoute
  '/app/peritos/': typeof AppPeritosIndexRoute
  '/app/processos/': typeof AppProcessosIndexRoute
  '/app/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/app/pericias/$id/editar': typeof AppPericiasIdEditarRoute
  '/app/peritos/$id/editar': typeof AppPeritosIdEditarRoute
  '/app/processos/$id/editar': typeof AppProcessosIdEditarRoute
  '/app/clientes/$id/': typeof AppClientesIdIndexRoute
  '/app/pericias/$id/': typeof AppPericiasIdIndexRoute
  '/app/peritos/$id/': typeof AppPeritosIdIndexRoute
  '/app/processos/$id/': typeof AppProcessosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contato'
    | '/criar-conta'
    | '/entrar'
    | '/planos'
    | '/produto'
    | '/profissoes'
    | '/recuperar-senha'
    | '/recursos'
    | '/seguranca'
    | '/servicos'
    | '/sobre'
    | '/app/agenda'
    | '/app/'
    | '/app/clientes/novo'
    | '/app/pericias/nova'
    | '/app/peritos/novo'
    | '/app/processos/novo'
    | '/app/clientes/'
    | '/app/pericias/'
    | '/app/peritos/'
    | '/app/processos/'
    | '/app/clientes/$id/editar'
    | '/app/pericias/$id/editar'
    | '/app/peritos/$id/editar'
    | '/app/processos/$id/editar'
    | '/app/clientes/$id/'
    | '/app/pericias/$id/'
    | '/app/peritos/$id/'
    | '/app/processos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/criar-conta'
    | '/entrar'
    | '/planos'
    | '/produto'
    | '/profissoes'
    | '/recuperar-senha'
    | '/recursos'
    | '/seguranca'
    | '/servicos'
    | '/sobre'
    | '/app/agenda'
    | '/app'
    | '/app/clientes/novo'
    | '/app/pericias/nova'
    | '/app/peritos/novo'
    | '/app/processos/novo'
    | '/app/clientes'
    | '/app/pericias'
    | '/app/peritos'
    | '/app/processos'
    | '/app/clientes/$id/editar'
    | '/app/pericias/$id/editar'
    | '/app/peritos/$id/editar'
    | '/app/processos/$id/editar'
    | '/app/clientes/$id'
    | '/app/pericias/$id'
    | '/app/peritos/$id'
    | '/app/processos/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contato'
    | '/criar-conta'
    | '/entrar'
    | '/planos'
    | '/produto'
    | '/profissoes'
    | '/recuperar-senha'
    | '/recursos'
    | '/seguranca'
    | '/servicos'
    | '/sobre'
    | '/app/agenda'
    | '/app/'
    | '/app/clientes/novo'
    | '/app/pericias/nova'
    | '/app/peritos/novo'
    | '/app/processos/novo'
    | '/app/clientes/'
    | '/app/pericias/'
    | '/app/peritos/'
    | '/app/processos/'
    | '/app/clientes/$id/editar'
    | '/app/pericias/$id/editar'
    | '/app/peritos/$id/editar'
    | '/app/processos/$id/editar'
    | '/app/clientes/$id/'
    | '/app/pericias/$id/'
    | '/app/peritos/$id/'
    | '/app/processos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  PlanosRoute: typeof PlanosRoute
  ProdutoRoute: typeof ProdutoRoute
  ProfissoesRoute: typeof ProfissoesRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RecursosRoute: typeof RecursosRoute
  SegurancaRoute: typeof SegurancaRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissoes': {
      id: '/profissoes'
      path: '/profissoes'
      fullPath: '/profissoes'
      preLoaderRoute: typeof ProfissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto': {
      id: '/produto'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processos/': {
      id: '/app/processos/'
      path: '/processos'
      fullPath: '/app/processos/'
      preLoaderRoute: typeof AppProcessosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/peritos/': {
      id: '/app/peritos/'
      path: '/peritos'
      fullPath: '/app/peritos/'
      preLoaderRoute: typeof AppPeritosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pericias/': {
      id: '/app/pericias/'
      path: '/pericias'
      fullPath: '/app/pericias/'
      preLoaderRoute: typeof AppPericiasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/': {
      id: '/app/clientes/'
      path: '/clientes'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processos/novo': {
      id: '/app/processos/novo'
      path: '/processos/novo'
      fullPath: '/app/processos/novo'
      preLoaderRoute: typeof AppProcessosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/peritos/novo': {
      id: '/app/peritos/novo'
      path: '/peritos/novo'
      fullPath: '/app/peritos/novo'
      preLoaderRoute: typeof AppPeritosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pericias/nova': {
      id: '/app/pericias/nova'
      path: '/pericias/nova'
      fullPath: '/app/pericias/nova'
      preLoaderRoute: typeof AppPericiasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/novo': {
      id: '/app/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/app/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processos/$id/': {
      id: '/app/processos/$id/'
      path: '/processos/$id'
      fullPath: '/app/processos/$id/'
      preLoaderRoute: typeof AppProcessosIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/peritos/$id/': {
      id: '/app/peritos/$id/'
      path: '/peritos/$id'
      fullPath: '/app/peritos/$id/'
      preLoaderRoute: typeof AppPeritosIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pericias/$id/': {
      id: '/app/pericias/$id/'
      path: '/pericias/$id'
      fullPath: '/app/pericias/$id/'
      preLoaderRoute: typeof AppPericiasIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/$id/': {
      id: '/app/clientes/$id/'
      path: '/clientes/$id'
      fullPath: '/app/clientes/$id/'
      preLoaderRoute: typeof AppClientesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processos/$id/editar': {
      id: '/app/processos/$id/editar'
      path: '/processos/$id/editar'
      fullPath: '/app/processos/$id/editar'
      preLoaderRoute: typeof AppProcessosIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/peritos/$id/editar': {
      id: '/app/peritos/$id/editar'
      path: '/peritos/$id/editar'
      fullPath: '/app/peritos/$id/editar'
      preLoaderRoute: typeof AppPeritosIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pericias/$id/editar': {
      id: '/app/pericias/$id/editar'
      path: '/pericias/$id/editar'
      fullPath: '/app/pericias/$id/editar'
      preLoaderRoute: typeof AppPericiasIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/$id/editar': {
      id: '/app/clientes/$id/editar'
      path: '/clientes/$id/editar'
      fullPath: '/app/clientes/$id/editar'
      preLoaderRoute: typeof AppClientesIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientesNovoRoute: typeof AppClientesNovoRoute
  AppPericiasNovaRoute: typeof AppPericiasNovaRoute
  AppPeritosNovoRoute: typeof AppPeritosNovoRoute
  AppProcessosNovoRoute: typeof AppProcessosNovoRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppPericiasIndexRoute: typeof AppPericiasIndexRoute
  AppPeritosIndexRoute: typeof AppPeritosIndexRoute
  AppProcessosIndexRoute: typeof AppProcessosIndexRoute
  AppClientesIdEditarRoute: typeof AppClientesIdEditarRoute
  AppPericiasIdEditarRoute: typeof AppPericiasIdEditarRoute
  AppPeritosIdEditarRoute: typeof AppPeritosIdEditarRoute
  AppProcessosIdEditarRoute: typeof AppProcessosIdEditarRoute
  AppClientesIdIndexRoute: typeof AppClientesIdIndexRoute
  AppPericiasIdIndexRoute: typeof AppPericiasIdIndexRoute
  AppPeritosIdIndexRoute: typeof AppPeritosIdIndexRoute
  AppProcessosIdIndexRoute: typeof AppProcessosIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientesNovoRoute: AppClientesNovoRoute,
  AppPericiasNovaRoute: AppPericiasNovaRoute,
  AppPeritosNovoRoute: AppPeritosNovoRoute,
  AppProcessosNovoRoute: AppProcessosNovoRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppPericiasIndexRoute: AppPericiasIndexRoute,
  AppPeritosIndexRoute: AppPeritosIndexRoute,
  AppProcessosIndexRoute: AppProcessosIndexRoute,
  AppClientesIdEditarRoute: AppClientesIdEditarRoute,
  AppPericiasIdEditarRoute: AppPericiasIdEditarRoute,
  AppPeritosIdEditarRoute: AppPeritosIdEditarRoute,
  AppProcessosIdEditarRoute: AppProcessosIdEditarRoute,
  AppClientesIdIndexRoute: AppClientesIdIndexRoute,
  AppPericiasIdIndexRoute: AppPericiasIdIndexRoute,
  AppPeritosIdIndexRoute: AppPeritosIdIndexRoute,
  AppProcessosIdIndexRoute: AppProcessosIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  PlanosRoute: PlanosRoute,
  ProdutoRoute: ProdutoRoute,
  ProfissoesRoute: ProfissoesRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RecursosRoute: RecursosRoute,
  SegurancaRoute: SegurancaRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
